### ISSUE TITLE
GPU Profiler Doesn't Update

### ISSUE THREAD

**Issue by andrejhronco** [cables-gl/cables_docs#608]
**Describe the bug**
<img width="824" alt="image" src="https://github.com/cables-gl/cables_docs/assets/1925905/dee60940-3f57-41fa-b398-c03db93fbb18">
The GPU Profiler data never updates, always 0ms / 0%. The draw calls seem to be listed correctly though.

**How To Reproduce**
1. Open Editor
2. Open GPU Profiler

**Platfowm**
 - macOS 14.1.1 / Chrome

**Comment by pandrr** [comment]
hi, thanks for the report. this was fixed in the latest cables update/release

**Comment by andrejhronco** [comment]
@pandrr maybe i'm not using it correctly but it's still not updating on either prod or dev
<img width="673" alt="image" src="https://github.com/cables-gl/cables_docs/assets/1925905/cec5509a-8649-437d-8673-ffe018f1f4f3">

**Comment by pandrr** [comment]
ah, forgot to mention: you need the performance op for it!

i will add a warning message to the view...
