### ISSUE TITLE
dev.cables.gl: Team op cannot be placed on dev.cables.gl and regular cables.gl

### ISSUE THREAD

**Issue by TobyKLight** [cables-gl/cables_docs#813]
**Describe the bug**
I created an op (twice now) in a team 
Part way through patching it disappears 
I can still see it in the op browser. 
When I try to recreate it I get an error in the log "no op....."

<img width="203" alt="image" src="https://github.com/user-attachments/assets/3f127b6a-13cc-4255-9208-f6b5dbe23164">

**How To Reproduce**
To reproduce 
- Join the team PipingHotOpenOps https://dev.cables.gl/team/659d237e6db3349a95ff0f38
- You can see on that page at the bottom FlipFlop is one of the ops 
- Create a new patch 
- Try and create a FlipFlop op

**Platform**
 - Chrome Desktop

**Comment by pandrr** [comment]
this should be fixed now.
you have an syntax error in your code and no exception was shown. you should be able to identify the error now.

this problem was ONLY happening on dev.cables.gl. next time please tell us that, maybe in the title of the issue somehow

**Comment by TobyKLight** [comment]
Hi 

I'm afraid it's not fixed for me.  Cannot create the node, open the code editor and fix the syntax error. 
Have reset cache. 

I get the following error on dev.cables.gl 
<img width="481" alt="ErrorOnDevCablesGL" src="https://github.com/user-attachments/assets/5a77a16a-6df6-48ff-8263-431d8e42a29f">


I'm not sure what you mean about the bug being only on dev.cables.gl. It never worked on regular cables.gl, and still doesn't. 
I updated the title and will add that info to the titles in future. 
<img width="643" alt="ErrorOnRegularCablesGl" src="https://github.com/user-attachments/assets/2815acf4-381b-45c9-9a0e-b529275dfcac">

**Comment by pandrr** [comment]
<img width="512" alt="Screenshot 2024-07-30 at 18 52 02" src="https://github.com/user-attachments/assets/c870d0d0-0f1c-4359-9906-ed4ff178b37e">

you are trying to use a variable called "result" but you only have a port variable called "outResult"

**Comment by TobyKLight** [comment]
Thanks for the tip.
The problem is not the error in the code itself. 

The problem I'm having is I cannot create a FlipFlop op in order to press the edit code button to update that error. 
Also the FlipFlip ops that I already placed in my original patch have disappeared.

If one syntax error lock you out from editing the code at all this is not ideal.

**Comment by pandrr** [comment]
you can reach an editor on the op page itself, or click the manage op icon in the op search

<img width="345" alt="Screenshot 2024-07-30 at 18 58 06" src="https://github.com/user-attachments/assets/9277ba72-41e8-470e-ae19-938862b16e13">

<img width="763" alt="Screenshot 2024-07-30 at 18 58 26" src="https://github.com/user-attachments/assets/d07acb5e-a6aa-47f2-a74e-02dfc9922674">

**Comment by pandrr** [comment]
<img width="911" alt="Screenshot 2024-07-30 at 18 58 48" src="https://github.com/user-attachments/assets/c822d95a-eae2-48ef-b1da-ab60765012f0">

**Comment by TobyKLight** [comment]
Ok, thanks. 

Honestly until now didn't know about those other methods for editing code.
